alias g='gcc -Wall -Werror -Wextra';
alias ls='ls -a';
alias norm='norminette -R CheckForbiddenSourceHeader';
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
export PS1="\e[31;1m\u \e[36;1m\w> \e[0m"
